Sprint 2
nikita11044/middle.messenger.praktikum.yandex pull request #2
Opened 2022-06-12 20:29 UTC by nikita11044

Каюсь, работа пока до конца не выполнена. Однако очень нужен фидбэк по тому, что есть. Подробности изложил в README в ветке main

2022-06-13 06:37 UTC, podlovchenko requested changes
Привет, по коду все хорошо, корректное использование типов
Есть замечания по работе системы, на странице логина поле логин не кликабельно, на странице регистрации нет валидации

2022-06-13 06:37 UTC, podlovchenko commented on package.json
> +    "start": "npm run build && node ./server.js"
Хорошо бы добавить команды для линтера

2022-06-13 06:37 UTC, podlovchenko commented on tsconfig.json
> +    // "disableReferencedProjectLoad": true,             /* Reduce the number of projects loaded automatically by TypeScript. */
В этом конфиге сложно ориентироваться, лучше оставить то, что используется

2022-06-13 06:49 UTC, podlovchenko commented on src/pages/login/login.ts
> +        this.setState(nextState);
Проблема фокуса здесь, происходить бесконечный перерендер, ищи проблему в использовании setState

2022-06-13 06:56 UTC, podlovchenko commented
По роутеру и стейту ничего плохого сказать не могу, но их все равно придется переделать, потому что в следующем задании будет необходимо сохранять роут в урле

2022-06-17 14:00 UTC, dmitrymorozoff reviewed
Привет) Спасибо за выполненную работу. В целом все неплохо, все задачи ТЗ выполнены, оставил несколько комментариев, которые можно было бы поправить. 

Работу принял. Удачи в дальнейшем)

2022-06-17 14:00 UTC, dmitrymorozoff commented on src/components/accessFormField/accessFormField.ts
> +    customValidationOption, formValue, value = '', label, inputType,
Здесь, чтобы не писать все свойства, можно воспользоваться [rest-оператором](https://learn.javascript.ru/rest-parameters-spread-operator)

2022-06-17 14:00 UTC, dmitrymorozoff commented on src/components/button/button.ts
> +  }: ButtonProps) {
props лучше типизировать через [generics](https://www.typescriptlang.org/docs/handbook/2/generics.html), так будет возможность точно передать в базовый блок, тип пропсов наследников.

Получится, что-то такое:
```
abstract class Block<Props extends {}> {
    private element: HTMLElement;
    private tagName: string;

    protected props: Props;

    public constructor(tagName: string = 'div', propsAndChildren: Props) {
        this.tagName = tagName;
        this.props = propsAndChildren;
    }
}

type ButtonProps = {
    onClick: () => {};
};

class Button extends Block<ButtonProps> {
    public constructor(props: ButtonProps) {
        super('div', props);
    }

    public onClick() {
        this.props.onClick();
    }
}
```

2022-06-17 14:00 UTC, dmitrymorozoff commented on src/pages/changePassword/changePassword.ts
> +                const data: Record<string, string> = Object.entries(this.refs).reduce((acc, [fieldName, ref]) => {
`data` не очень информативное название, название переменной должно отражать содержание того, что в ней будет лежать

2022-06-19 10:08 UTC, nikita11044 commented
Большое спасибо за отзыв, немного подправил по замечаниям. Единственный нюанс - сейчас выгружу работу на платформу повторно, т. к. в прошлый раз на платформе сломались тесты.

2022-06-26 13:57 UTC, merged